import { getLSGameId } from "../dojo/utils/getLSGameId";
import { IGameContext } from "./GameProvider";

export const gameProviderDefaults: IGameContext = {
  gameId: getLSGameId(),
  executeCreateGame: () => {},
  gameLoading: false,
  play: () => {},
  discardAnimation: false,
  playAnimation: false,
  discard: () => {},
  changeModifierCard: () =>
    new Promise((resolve) => resolve({ success: false, cards: [] })),
  error: false,
  clearPreSelection: () => {},
  addModifier: (_, __) => {},
  roundRewards: undefined,
  onShopSkip: () => {},
  sellSpecialCard: () => new Promise((resolve) => resolve(false)),
  checkOrCreateGame: () => {},
  restartGame: () => {},
  lockRedirection: false,
  specialCards: [],
  playIsNeon: false,
  destroyedSpecialCardId: undefined,
  setDestroyedSpecialCardId: () => {},
  levelUpHand: undefined,
  setLevelUpHand: () => {},
  specialSwitcherOn: true,
  toggleSpecialSwitcher: () => {},
  showRages: () => {},
  showSpecials: () => {},
  powerUps: [],
  removePowerUp: (_) => {},
  preselectedPowerUps: [],
  setPreselectedPowerUps: (_) => {},
  togglePreselectedPowerUp: (_) => {},
  powerUpIsPreselected: (_) => false,
  setPowerUps: (_) => {},
  addPowerUp: (_) => {},
  maxSpecialCards: 7,
  maxPowerUpSlots: 4,
  setGameId: (_) => {},
  resetLevel: () => {},
  cardTransformationLock: false,
  nodeRound: 0,
  prepareNewGame: () => {},
  surrenderGame: (_) => {},
};
