export enum DojoEvents {
  CREATE_GAME = "CreateGameEvent",
  CARD_SCORE = "CardScoreEvent",
  PLAY_WIN_GAME = "PlayWinGameEvent",
  PLAY_GAME_OVER = "PlayGameOverEvent",
  ROUND_SCORE = "RoundScoreEvent",
  DETAIL_EARNED = "DetailEarnedEvent",
  MODIFIER_CARD_SUIT = "ModifierCardSuitEvent",
  POWER_UP = "PowerUpEvent",
  GAME_POWER_UP = "GamePowerUpEvent",

  POKER_HAND = "PokerHandEvent",
  SPECIAL_MODIFIER_POINTS = "SpecialModifierPointsEvent",
  SPECIAL_MODIFIER_MULTI = "SpecialModifierMultiEvent",
  SPECIAL_POKER_HAND = "SpecialPokerHandEvent",
  SPECIAL_MODIFIER_SUIT = "SpecialModifierSuitEvent",
  CURRENT_HAND = "CurrentHandEvent",
  NEON_POKER_HAND = "NeonPokerHandEvent",
  SPECIAL_CASH = "SpecialCashEvent",
  SECOND_CHANCE = "SecondChanceEvent",
  DESTROYED_SPECIAL_CARD = "DestroyedSpecialCardEvent",
  POKER_HAND_LEVEL_UP = "PokerHandLevelUpEvent",
  LEVEL_UP_HAND = "LevelUpHandEvent",
  MODIFIER_CARD_NEON = "ModifierCardNeonEvent",
  SPECIAL_NEON_CARD = "SpecialNeonCardEvent",
  CARD_PLAY = "CardPlayEvent",
  CARD_ACTIVATE = "CardActivateEvent",
  SHOP_TIER_UNLOCKED = "TierUnlockedEvent",
  POST_ACTION = "PostActionEvent",
  FORCED_HAND_DISCARD = "ForcedHandDiscardEvent",

  ACHIEVEMENT_COMPLETE = "AchievementCompletedEvent",
  DAILY_MISSION_COMPLETE = "MissionCompletedV2Event",
  LEVEL_COMPLETE = "LevelCompletionXPEvent",
}
