export const GAME_ID = 'GAME_ID'
export const LAST_GAME_ID = 'LAST_GAME_ID'
export const SOUND_OFF = 'SOUND_OFF'
export const LOGGED_USER = 'LOGGED_USER'
export const SORT_BY_SUIT = 'SORT_BY_SUIT'
export const SKIP_TUTORIAL = 'SKIP_TUTORIAL'
export const SKIP_TUTORIAL_GAME = 'SKIP_TUTORIAL_GAME'